version: 2
multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "supply-chain"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
    labels:
      - "dependencies"
      - "supply-chain"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
    labels:
      - "dependencies"
      - "supply-chain"
