from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / ".github" / "compatibility-matrix.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "operations" / "compatibility-matrix.md"


def _render_matrix_rows(rows: list[dict[str, str]]) -> list[str]:
    rendered = [
        "| Python | Kafka baseline | Client | Verification | Workflow | Notes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        rendered.append(
            "| %(python_version)s | %(kafka_image)s | %(client_label)s | %(verification)s | `compatibility-matrix.yml` | %(notes)s |"
            % {
                "python_version": row["python-version"],
                "kafka_image": row["kafka-image"],
                "client_label": row["client-label"],
                "verification": row["verification"],
                "notes": row["notes"],
            }
        )
    return rendered


def render_markdown(payload: dict[str, object]) -> str:
    verified_rows = payload["include"]

    if not isinstance(verified_rows, list):
        raise ValueError("include must be a list")

    lines = [
        "<!-- Generated by scripts/compatibility_matrix.py; edit .github/compatibility-matrix.json instead. -->",
        "# Compatibility Matrix",
        "",
        "This document is generated from `.github/compatibility-matrix.json`.",
        "It exists so the support story is tied to the same manifest consumed by `.github/workflows/compatibility-matrix.yml`.",
        "",
        "## Verified combinations",
        "",
        *_render_matrix_rows(verified_rows),
        "",
        "## Workflow behavior",
        "",
        "- `.github/workflows/compatibility-matrix.yml` loads the manifest dynamically with `fromJSON(...)`.",
        "- Each row boots Kafka via `.github/e2e.compose.yml`, honors `KAFKA_IMAGE`, and runs the broker-backed E2E target declared in the manifest.",
        "- The workflow also runs `scripts/compatibility_matrix.py --check` so the tracked markdown cannot drift from the manifest.",
        "- `.github/workflows/release-verify.yml` also runs `scripts/compatibility_matrix.py --check`, so release verification catches manifest/doc drift before publishing.",
        "",
        "## Scope notes",
        "",
        "- Rows listed above are the combinations actively verified today.",
        "- Other broker distributions or older client/broker combinations remain best-effort until the manifest is widened and automated.",
        "- Python `<3.12` remains outside the package metadata and CI contract.",
    ]
    return "\n".join(lines)


def load_payload(input_path: Path) -> dict[str, object]:
    return json.loads(input_path.read_text(encoding="utf-8"))


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or validate the compatibility matrix markdown."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Path to the JSON source file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to the generated markdown file.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the generated markdown does not match the tracked file.",
    )
    args = parser.parse_args()

    input_path = args.input
    payload = load_payload(input_path)
    rendered = render_markdown(payload)
    output_path = args.output

    if args.check:
        if not output_path.exists():
            raise SystemExit(
                "%s is missing; run scripts/compatibility_matrix.py"
                % _display_path(output_path)
            )
        existing = output_path.read_text(encoding="utf-8")
        if existing != rendered + "\n":
            raise SystemExit(
                "%s is out of date; run scripts/compatibility_matrix.py"
                % _display_path(output_path)
            )
        print("%s is up to date" % _display_path(output_path))
        return 0

    output_path.write_text(rendered + "\n", encoding="utf-8")
    print("wrote %s" % _display_path(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
